# Generated by Django 4.0.1 on 2022-01-21 15:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20, verbose_name='Name')),
                ('task_desciption', models.TextField(default=None, verbose_name='Description')),
                ('task_datetime', models.DateTimeField(default=datetime.datetime(2022, 1, 21, 20, 45, 11, 167569), verbose_name='Date and Time')),
                ('task_pinned', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Pin this task?')),
                ('task_id', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['task_name', 'task_description', 'task_datetime'], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taskdetail',
            fields=[
                ('task_status', models.CharField(choices=[('Complete', 'Completed'), ('Incomplete', 'Not completed')], default='Incomplete', max_length=15, verbose_name='Status')),
                ('task_challenge', models.TextField(default=None, verbose_name='Challenges in task')),
                ('task_eta', models.IntegerField(default=0, help_text='Estimated time to completion in minutes', verbose_name='ET for completion')),
                ('task_percent', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('task', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Task', serialize=False, to='Task.task')),
            ],
        ),
    ]
