# Generated by Django 4.0.1 on 2022-01-21 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_alter_task_task_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 20, 45, 38, 545978), verbose_name='Date and Time'),
        ),
    ]
