# Generated by Django 4.0.1 on 2022-01-21 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_alter_task_task_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['task_datetime']},
        ),
        migrations.AlterModelOptions(
            name='taskdetail',
            options={'verbose_name': 'Task Detail'},
        ),
        migrations.AlterField(
            model_name='task',
            name='task_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 21, 6, 59, 979690), verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_desciption',
            field=models.TextField(default=None, null=True, verbose_name='Description'),
        ),
    ]
