# Generated by Django 4.0.1 on 2022-01-22 12:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_alter_task_options_alter_taskdetail_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 18, 14, 5, 165916), verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_desciption',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['task_name', 'task_datetime'], primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Task', serialize=False, to='Task.task'),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='task_challenge',
            field=models.TextField(blank=True, default=None, verbose_name='Challenges in task'),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='task_status',
            field=models.CharField(choices=[('Complete', 'Completed'), ('Incomplete', 'Not completed')], default='Incomplete', editable=False, max_length=15, verbose_name='Status'),
        ),
    ]
