# Generated by Django 4.0.1 on 2022-01-22 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0006_remove_task_id_alter_task_task_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 3, 0, 35, 418613), verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_desciption',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='task_challenge',
            field=models.TextField(blank=True, default='', verbose_name='Challenges in task'),
        ),
    ]
