# Generated by Django 4.0.1 on 2022-01-22 21:36

import datetime
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0007_alter_task_task_datetime_alter_task_task_desciption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 3, 6, 7, 62546), verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default='', editable=False, populate_from=['task_name', 'task_datetime'], primary_key=True, serialize=False, unique=True),
        ),
    ]
