# Generated by Django 4.0.1 on 2022-01-22 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0010_alter_task_task_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 3, 25, 59, 223819), verbose_name='Date and Time'),
        ),
    ]
