# Generated by Django 4.0.1 on 2022-01-22 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0012_alter_task_task_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 4, 20, 30, 333490), verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='task_status',
            field=models.CharField(choices=[('Complete', 'Completed'), ('Incomplete', 'Not completed')], default='Incomplete', max_length=15, verbose_name='Status'),
        ),
    ]
